/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.account.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AccountBankDetailsItem
 */
@JsonPropertyOrder( {
        AccountBankDetailsItem.JSON_PROPERTY_IBAN,
        AccountBankDetailsItem.JSON_PROPERTY_BIC,
        AccountBankDetailsItem.JSON_PROPERTY_ACCOUNT_NO,
        AccountBankDetailsItem.JSON_PROPERTY_SORT_CODE,
        AccountBankDetailsItem.JSON_PROPERTY_ROUTING_NUMBER,
        AccountBankDetailsItem.JSON_PROPERTY_BENEFICIARY,
        AccountBankDetailsItem.JSON_PROPERTY_BENEFICIARY_ADDRESS,
        AccountBankDetailsItem.JSON_PROPERTY_BANK_COUNTRY,
        AccountBankDetailsItem.JSON_PROPERTY_POOLED,
        AccountBankDetailsItem.JSON_PROPERTY_UNIQUE_REFERENCE,
        AccountBankDetailsItem.JSON_PROPERTY_SCHEMES,
        AccountBankDetailsItem.JSON_PROPERTY_ESTIMATED_TIME
} )
public class AccountBankDetailsItem
{
    public static final String JSON_PROPERTY_IBAN = "iban";

    public static final String JSON_PROPERTY_BIC = "bic";

    public static final String JSON_PROPERTY_ACCOUNT_NO = "account_no";

    public static final String JSON_PROPERTY_SORT_CODE = "sort_code";

    public static final String JSON_PROPERTY_ROUTING_NUMBER = "routing_number";

    public static final String JSON_PROPERTY_BENEFICIARY = "beneficiary";

    public static final String JSON_PROPERTY_BENEFICIARY_ADDRESS = "beneficiary_address";

    public static final String JSON_PROPERTY_BANK_COUNTRY = "bank_country";

    public static final String JSON_PROPERTY_POOLED = "pooled";

    public static final String JSON_PROPERTY_UNIQUE_REFERENCE = "unique_reference";

    public static final String JSON_PROPERTY_SCHEMES = "schemes";

    public static final String JSON_PROPERTY_ESTIMATED_TIME = "estimated_time";

    private String iban;

    private String bic;

    private String accountNo;

    private String sortCode;

    private String routingNumber;

    private String beneficiary;

    private BeneficiaryAddress beneficiaryAddress;

    private String bankCountry;

    private Boolean pooled;

    private String uniqueReference;

    private List<PaymentSystem> schemes = new ArrayList<>();

    private EstimatedTime estimatedTime;


    public AccountBankDetailsItem iban( String iban )
    {

        this.iban = iban;
        return this;
    }

    /**
     * Get iban
     *
     * @return iban
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_IBAN )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getIban()
    {
        return iban;
    }

    public void setIban( String iban )
    {
        this.iban = iban;
    }

    public AccountBankDetailsItem bic( String bic )
    {

        this.bic = bic;
        return this;
    }

    /**
     * Get bic
     *
     * @return bic
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_BIC )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getBic()
    {
        return bic;
    }

    public void setBic( String bic )
    {
        this.bic = bic;
    }

    public AccountBankDetailsItem accountNo( String accountNo )
    {

        this.accountNo = accountNo;
        return this;
    }

    /**
     * Get accountNo
     *
     * @return accountNo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_ACCOUNT_NO )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getAccountNo()
    {
        return accountNo;
    }

    public void setAccountNo( String accountNo )
    {
        this.accountNo = accountNo;
    }

    public AccountBankDetailsItem sortCode( String sortCode )
    {

        this.sortCode = sortCode;
        return this;
    }

    /**
     * Get sortCode
     *
     * @return sortCode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_SORT_CODE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getSortCode()
    {
        return sortCode;
    }

    public void setSortCode( String sortCode )
    {
        this.sortCode = sortCode;
    }

    public AccountBankDetailsItem routingNumber( String routingNumber )
    {

        this.routingNumber = routingNumber;
        return this;
    }

    /**
     * Get routingNumber
     *
     * @return routingNumber
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_ROUTING_NUMBER )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getRoutingNumber()
    {
        return routingNumber;
    }

    public void setRoutingNumber( String routingNumber )
    {
        this.routingNumber = routingNumber;
    }

    public AccountBankDetailsItem beneficiary( String beneficiary )
    {

        this.beneficiary = beneficiary;
        return this;
    }

    /**
     * Get beneficiary
     *
     * @return beneficiary
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_BENEFICIARY )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public String getBeneficiary()
    {
        return beneficiary;
    }

    public void setBeneficiary( String beneficiary )
    {
        this.beneficiary = beneficiary;
    }

    public AccountBankDetailsItem beneficiaryAddress( BeneficiaryAddress beneficiaryAddress )
    {

        this.beneficiaryAddress = beneficiaryAddress;
        return this;
    }

    /**
     * Get beneficiaryAddress
     *
     * @return beneficiaryAddress
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_BENEFICIARY_ADDRESS )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public BeneficiaryAddress getBeneficiaryAddress()
    {
        return beneficiaryAddress;
    }

    public void setBeneficiaryAddress( BeneficiaryAddress beneficiaryAddress )
    {
        this.beneficiaryAddress = beneficiaryAddress;
    }

    public AccountBankDetailsItem bankCountry( String bankCountry )
    {

        this.bankCountry = bankCountry;
        return this;
    }

    /**
     * Get bankCountry
     *
     * @return bankCountry
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_BANK_COUNTRY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getBankCountry()
    {
        return bankCountry;
    }

    public void setBankCountry( String bankCountry )
    {
        this.bankCountry = bankCountry;
    }

    public AccountBankDetailsItem pooled( Boolean pooled )
    {

        this.pooled = pooled;
        return this;
    }

    /**
     * Get pooled
     *
     * @return pooled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_POOLED )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public Boolean getPooled()
    {
        return pooled;
    }

    public void setPooled( Boolean pooled )
    {
        this.pooled = pooled;
    }

    public AccountBankDetailsItem uniqueReference( String uniqueReference )
    {

        this.uniqueReference = uniqueReference;
        return this;
    }

    /**
     * Get uniqueReference
     *
     * @return uniqueReference
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_UNIQUE_REFERENCE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getUniqueReference()
    {
        return uniqueReference;
    }

    public void setUniqueReference( String uniqueReference )
    {
        this.uniqueReference = uniqueReference;
    }

    public AccountBankDetailsItem schemes( List<PaymentSystem> schemes )
    {

        this.schemes = schemes;
        return this;
    }

    public AccountBankDetailsItem addSchemesItem( PaymentSystem schemesItem )
    {
        this.schemes.add( schemesItem );
        return this;
    }

    /**
     * Get schemes
     *
     * @return schemes
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_SCHEMES )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public List<PaymentSystem> getSchemes()
    {
        return schemes;
    }

    public void setSchemes( List<PaymentSystem> schemes )
    {
        this.schemes = schemes;
    }

    public AccountBankDetailsItem estimatedTime( EstimatedTime estimatedTime )
    {

        this.estimatedTime = estimatedTime;
        return this;
    }

    /**
     * Get estimatedTime
     *
     * @return estimatedTime
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_ESTIMATED_TIME )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public EstimatedTime getEstimatedTime()
    {
        return estimatedTime;
    }

    public void setEstimatedTime( EstimatedTime estimatedTime )
    {
        this.estimatedTime = estimatedTime;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        AccountBankDetailsItem accountBankDetailsItem = ( AccountBankDetailsItem ) o;
        return Objects.equals( this.iban, accountBankDetailsItem.iban ) &&
                Objects.equals( this.bic, accountBankDetailsItem.bic ) &&
                Objects.equals( this.accountNo, accountBankDetailsItem.accountNo ) &&
                Objects.equals( this.sortCode, accountBankDetailsItem.sortCode ) &&
                Objects.equals( this.routingNumber, accountBankDetailsItem.routingNumber ) &&
                Objects.equals( this.beneficiary, accountBankDetailsItem.beneficiary ) &&
                Objects.equals( this.beneficiaryAddress, accountBankDetailsItem.beneficiaryAddress ) &&
                Objects.equals( this.bankCountry, accountBankDetailsItem.bankCountry ) &&
                Objects.equals( this.pooled, accountBankDetailsItem.pooled ) &&
                Objects.equals( this.uniqueReference, accountBankDetailsItem.uniqueReference ) &&
                Objects.equals( this.schemes, accountBankDetailsItem.schemes ) &&
                Objects.equals( this.estimatedTime, accountBankDetailsItem.estimatedTime );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( iban, bic, accountNo, sortCode, routingNumber, beneficiary, beneficiaryAddress, bankCountry, pooled, uniqueReference, schemes, estimatedTime );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class AccountBankDetailsItem {\n" );
        sb.append( "    iban: " ).append( toIndentedString( iban ) ).append( "\n" );
        sb.append( "    bic: " ).append( toIndentedString( bic ) ).append( "\n" );
        sb.append( "    accountNo: " ).append( toIndentedString( accountNo ) ).append( "\n" );
        sb.append( "    sortCode: " ).append( toIndentedString( sortCode ) ).append( "\n" );
        sb.append( "    routingNumber: " ).append( toIndentedString( routingNumber ) ).append( "\n" );
        sb.append( "    beneficiary: " ).append( toIndentedString( beneficiary ) ).append( "\n" );
        sb.append( "    beneficiaryAddress: " ).append( toIndentedString( beneficiaryAddress ) ).append( "\n" );
        sb.append( "    bankCountry: " ).append( toIndentedString( bankCountry ) ).append( "\n" );
        sb.append( "    pooled: " ).append( toIndentedString( pooled ) ).append( "\n" );
        sb.append( "    uniqueReference: " ).append( toIndentedString( uniqueReference ) ).append( "\n" );
        sb.append( "    schemes: " ).append( toIndentedString( schemes ) ).append( "\n" );
        sb.append( "    estimatedTime: " ).append( toIndentedString( estimatedTime ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

