/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.counterparty.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BeneficiaryAddress
 */
@JsonPropertyOrder( {
        BeneficiaryAddress.JSON_PROPERTY_STREET_LINE1,
        BeneficiaryAddress.JSON_PROPERTY_STREET_LINE2,
        BeneficiaryAddress.JSON_PROPERTY_REGION,
        BeneficiaryAddress.JSON_PROPERTY_CITY,
        BeneficiaryAddress.JSON_PROPERTY_COUNTRY,
        BeneficiaryAddress.JSON_PROPERTY_POSTCODE
} )
public class BeneficiaryAddress
{
    public static final String JSON_PROPERTY_STREET_LINE1 = "street_line1";

    public static final String JSON_PROPERTY_STREET_LINE2 = "street_line2";

    public static final String JSON_PROPERTY_REGION = "region";

    public static final String JSON_PROPERTY_CITY = "city";

    public static final String JSON_PROPERTY_COUNTRY = "country";

    public static final String JSON_PROPERTY_POSTCODE = "postcode";

    private String streetLine1;

    private String streetLine2;

    private String region;

    private String city;

    private String country;

    private String postcode;

    public BeneficiaryAddress streetLine1( String streetLine1 )
    {

        this.streetLine1 = streetLine1;
        return this;
    }

    /**
     * Get streetLine1
     *
     * @return streetLine1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_STREET_LINE1 )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getStreetLine1()
    {
        return streetLine1;
    }

    public void setStreetLine1( String streetLine1 )
    {
        this.streetLine1 = streetLine1;
    }

    public BeneficiaryAddress streetLine2( String streetLine2 )
    {

        this.streetLine2 = streetLine2;
        return this;
    }

    /**
     * Get streetLine2
     *
     * @return streetLine2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_STREET_LINE2 )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getStreetLine2()
    {
        return streetLine2;
    }

    public void setStreetLine2( String streetLine2 )
    {
        this.streetLine2 = streetLine2;
    }

    public BeneficiaryAddress region( String region )
    {

        this.region = region;
        return this;
    }

    /**
     * Get region
     *
     * @return region
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_REGION )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getRegion()
    {
        return region;
    }

    public void setRegion( String region )
    {
        this.region = region;
    }

    public BeneficiaryAddress city( String city )
    {

        this.city = city;
        return this;
    }

    /**
     * Get city
     *
     * @return city
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_CITY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getCity()
    {
        return city;
    }

    public void setCity( String city )
    {
        this.city = city;
    }

    public BeneficiaryAddress country( String country )
    {

        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_COUNTRY )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public String getCountry()
    {
        return country;
    }

    public void setCountry( String country )
    {
        this.country = country;
    }

    public BeneficiaryAddress postcode( String postcode )
    {

        this.postcode = postcode;
        return this;
    }

    /**
     * Get postcode
     *
     * @return postcode
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_POSTCODE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public String getPostcode()
    {
        return postcode;
    }

    public void setPostcode( String postcode )
    {
        this.postcode = postcode;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        BeneficiaryAddress beneficiaryAddress = ( BeneficiaryAddress ) o;
        return Objects.equals( this.streetLine1, beneficiaryAddress.streetLine1 ) &&
                Objects.equals( this.streetLine2, beneficiaryAddress.streetLine2 ) &&
                Objects.equals( this.region, beneficiaryAddress.region ) &&
                Objects.equals( this.city, beneficiaryAddress.city ) &&
                Objects.equals( this.country, beneficiaryAddress.country ) &&
                Objects.equals( this.postcode, beneficiaryAddress.postcode );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( streetLine1, streetLine2, region, city, country, postcode );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class BeneficiaryAddress {\n" );
        sb.append( "    streetLine1: " ).append( toIndentedString( streetLine1 ) ).append( "\n" );
        sb.append( "    streetLine2: " ).append( toIndentedString( streetLine2 ) ).append( "\n" );
        sb.append( "    region: " ).append( toIndentedString( region ) ).append( "\n" );
        sb.append( "    city: " ).append( toIndentedString( city ) ).append( "\n" );
        sb.append( "    country: " ).append( toIndentedString( country ) ).append( "\n" );
        sb.append( "    postcode: " ).append( toIndentedString( postcode ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

