/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.counterparty.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Counterparty
 */
@JsonPropertyOrder( {
        Counterparty.JSON_PROPERTY_ID,
        Counterparty.JSON_PROPERTY_NAME,
        Counterparty.JSON_PROPERTY_PHONE,
        Counterparty.JSON_PROPERTY_PROFILE_TYPE,
        Counterparty.JSON_PROPERTY_COUNTRY,
        Counterparty.JSON_PROPERTY_STATE,
        Counterparty.JSON_PROPERTY_CREATED_AT,
        Counterparty.JSON_PROPERTY_UPDATED_AT,
        Counterparty.JSON_PROPERTY_ACCOUNTS
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.366+01:00[Europe/Bratislava]" )
public class Counterparty
{
    public static final String JSON_PROPERTY_ID = "id";

    public static final String JSON_PROPERTY_NAME = "name";

    public static final String JSON_PROPERTY_PHONE = "phone";

    public static final String JSON_PROPERTY_PROFILE_TYPE = "profile_type";

    public static final String JSON_PROPERTY_COUNTRY = "country";

    public static final String JSON_PROPERTY_STATE = "state";

    public static final String JSON_PROPERTY_CREATED_AT = "created_at";

    public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";

    public static final String JSON_PROPERTY_ACCOUNTS = "accounts";

    private UUID id;

    private String name;

    private String phone;

    private ProfileType profileType;

    private String country;

    private StateEnum state;

    private OffsetDateTime createdAt;

    private OffsetDateTime updatedAt;

    private List<CounterpartyAccount> accounts = null;

    public Counterparty id( UUID id )
    {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public UUID getId()
    {
        return id;
    }

    public void setId( UUID id )
    {
        this.id = id;
    }

    public Counterparty name( String name )
    {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_NAME )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public String getName()
    {
        return name;
    }

    public void setName( String name )
    {
        this.name = name;
    }

    public Counterparty phone( String phone )
    {

        this.phone = phone;
        return this;
    }

    /**
     * Get phone
     *
     * @return phone
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_PHONE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getPhone()
    {
        return phone;
    }

    public void setPhone( String phone )
    {
        this.phone = phone;
    }

    public Counterparty profileType( ProfileType profileType )
    {

        this.profileType = profileType;
        return this;
    }

    /**
     * Get profileType
     *
     * @return profileType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_PROFILE_TYPE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public ProfileType getProfileType()
    {
        return profileType;
    }

    public void setProfileType( ProfileType profileType )
    {
        this.profileType = profileType;
    }

    public Counterparty country( String country )
    {

        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_COUNTRY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getCountry()
    {
        return country;
    }

    public void setCountry( String country )
    {
        this.country = country;
    }

    public Counterparty state( StateEnum state )
    {

        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_STATE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public StateEnum getState()
    {
        return state;
    }

    public void setState( StateEnum state )
    {
        this.state = state;
    }

    public Counterparty createdAt( OffsetDateTime createdAt )
    {

        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_CREATED_AT )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public OffsetDateTime getCreatedAt()
    {
        return createdAt;
    }

    public void setCreatedAt( OffsetDateTime createdAt )
    {
        this.createdAt = createdAt;
    }

    public Counterparty updatedAt( OffsetDateTime updatedAt )
    {

        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_UPDATED_AT )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public OffsetDateTime getUpdatedAt()
    {
        return updatedAt;
    }

    public void setUpdatedAt( OffsetDateTime updatedAt )
    {
        this.updatedAt = updatedAt;
    }

    public Counterparty accounts( List<CounterpartyAccount> accounts )
    {

        this.accounts = accounts;
        return this;
    }

    public Counterparty addAccountsItem( CounterpartyAccount accountsItem )
    {
        if ( this.accounts == null )
        {
            this.accounts = new ArrayList<>();
        }
        this.accounts.add( accountsItem );
        return this;
    }

    /**
     * Get accounts
     *
     * @return accounts
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_ACCOUNTS )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public List<CounterpartyAccount> getAccounts()
    {
        return accounts;
    }

    public void setAccounts( List<CounterpartyAccount> accounts )
    {
        this.accounts = accounts;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        Counterparty counterparty = ( Counterparty ) o;
        return Objects.equals( this.id, counterparty.id ) &&
                Objects.equals( this.name, counterparty.name ) &&
                Objects.equals( this.phone, counterparty.phone ) &&
                Objects.equals( this.profileType, counterparty.profileType ) &&
                Objects.equals( this.country, counterparty.country ) &&
                Objects.equals( this.state, counterparty.state ) &&
                Objects.equals( this.createdAt, counterparty.createdAt ) &&
                Objects.equals( this.updatedAt, counterparty.updatedAt ) &&
                Objects.equals( this.accounts, counterparty.accounts );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( id, name, phone, profileType, country, state, createdAt, updatedAt, accounts );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class Counterparty {\n" );
        sb.append( "    id: " ).append( toIndentedString( id ) ).append( "\n" );
        sb.append( "    name: " ).append( toIndentedString( name ) ).append( "\n" );
        sb.append( "    phone: " ).append( toIndentedString( phone ) ).append( "\n" );
        sb.append( "    profileType: " ).append( toIndentedString( profileType ) ).append( "\n" );
        sb.append( "    country: " ).append( toIndentedString( country ) ).append( "\n" );
        sb.append( "    state: " ).append( toIndentedString( state ) ).append( "\n" );
        sb.append( "    createdAt: " ).append( toIndentedString( createdAt ) ).append( "\n" );
        sb.append( "    updatedAt: " ).append( toIndentedString( updatedAt ) ).append( "\n" );
        sb.append( "    accounts: " ).append( toIndentedString( accounts ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

    /**
     * Gets or Sets state
     */
    public enum StateEnum
    {
        CREATED( "created" ),

        DRAFT( "draft" ),

        DELETED( "deleted" );

        private String value;

        StateEnum( String value )
        {
            this.value = value;
        }

        @JsonCreator
        public static StateEnum fromValue( String value )
        {
            for ( StateEnum b : StateEnum.values() )
            {
                if ( b.value.equals( value ) )
                {
                    return b;
                }
            }
            throw new IllegalArgumentException( "Unexpected value '" + value + "'" );
        }

        @JsonValue
        public String getValue()
        {
            return value;
        }

        @Override
        public String toString()
        {
            return String.valueOf( value );
        }
    }

}

