/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.counterparty.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * IndividualName
 */
@JsonPropertyOrder( {
        IndividualName.JSON_PROPERTY_FIRST_NAME,
        IndividualName.JSON_PROPERTY_LAST_NAME
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.366+01:00[Europe/Bratislava]" )
public class IndividualName
{
    public static final String JSON_PROPERTY_FIRST_NAME = "first_name";

    public static final String JSON_PROPERTY_LAST_NAME = "last_name";

    private String firstName;

    private String lastName;


    public IndividualName firstName( String firstName )
    {

        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     *
     * @return firstName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_FIRST_NAME )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getFirstName()
    {
        return firstName;
    }


    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }


    public IndividualName lastName( String lastName )
    {

        this.lastName = lastName;
        return this;
    }

    /**
     * Get lastName
     *
     * @return lastName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_LAST_NAME )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getLastName()
    {
        return lastName;
    }


    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }


    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        IndividualName individualName = ( IndividualName ) o;
        return Objects.equals( this.firstName, individualName.firstName ) &&
                Objects.equals( this.lastName, individualName.lastName );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( firstName, lastName );
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class IndividualName {\n" );
        sb.append( "    firstName: " ).append( toIndentedString( firstName ) ).append( "\n" );
        sb.append( "    lastName: " ).append( toIndentedString( lastName ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

