/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.exchange.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ExchangeRateResponse
 */
@JsonPropertyOrder( {
        ExchangeRateResponse.JSON_PROPERTY_FROM,
        ExchangeRateResponse.JSON_PROPERTY_TO,
        ExchangeRateResponse.JSON_PROPERTY_RATE,
        ExchangeRateResponse.JSON_PROPERTY_FEE,
        ExchangeRateResponse.JSON_PROPERTY_RATE_DATE
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.813+01:00[Europe/Bratislava]" )
public class ExchangeRateResponse
{
    public static final String JSON_PROPERTY_FROM = "from";

    public static final String JSON_PROPERTY_TO = "to";

    public static final String JSON_PROPERTY_RATE = "rate";

    public static final String JSON_PROPERTY_FEE = "fee";

    public static final String JSON_PROPERTY_RATE_DATE = "rate_date";

    private Amount from;

    private Amount to;

    private Double rate;

    private Amount fee;

    private OffsetDateTime rateDate;


    public ExchangeRateResponse from( Amount from )
    {

        this.from = from;
        return this;
    }

    /**
     * Get from
     *
     * @return from
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_FROM )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Amount getFrom()
    {
        return from;
    }


    public void setFrom( Amount from )
    {
        this.from = from;
    }


    public ExchangeRateResponse to( Amount to )
    {

        this.to = to;
        return this;
    }

    /**
     * Get to
     *
     * @return to
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_TO )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Amount getTo()
    {
        return to;
    }


    public void setTo( Amount to )
    {
        this.to = to;
    }


    public ExchangeRateResponse rate( Double rate )
    {

        this.rate = rate;
        return this;
    }

    /**
     * Get rate
     *
     * @return rate
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_RATE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Double getRate()
    {
        return rate;
    }


    public void setRate( Double rate )
    {
        this.rate = rate;
    }


    public ExchangeRateResponse fee( Amount fee )
    {

        this.fee = fee;
        return this;
    }

    /**
     * Get fee
     *
     * @return fee
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_FEE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Amount getFee()
    {
        return fee;
    }


    public void setFee( Amount fee )
    {
        this.fee = fee;
    }


    public ExchangeRateResponse rateDate( OffsetDateTime rateDate )
    {

        this.rateDate = rateDate;
        return this;
    }

    /**
     * Get rateDate
     *
     * @return rateDate
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_RATE_DATE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public OffsetDateTime getRateDate()
    {
        return rateDate;
    }


    public void setRateDate( OffsetDateTime rateDate )
    {
        this.rateDate = rateDate;
    }


    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        ExchangeRateResponse exchangeRateResponse = ( ExchangeRateResponse ) o;
        return Objects.equals( this.from, exchangeRateResponse.from ) &&
                Objects.equals( this.to, exchangeRateResponse.to ) &&
                Objects.equals( this.rate, exchangeRateResponse.rate ) &&
                Objects.equals( this.fee, exchangeRateResponse.fee ) &&
                Objects.equals( this.rateDate, exchangeRateResponse.rateDate );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( from, to, rate, fee, rateDate );
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class ExchangeRateResponse {\n" );
        sb.append( "    from: " ).append( toIndentedString( from ) ).append( "\n" );
        sb.append( "    to: " ).append( toIndentedString( to ) ).append( "\n" );
        sb.append( "    rate: " ).append( toIndentedString( rate ) ).append( "\n" );
        sb.append( "    fee: " ).append( toIndentedString( fee ) ).append( "\n" );
        sb.append( "    rateDate: " ).append( toIndentedString( rateDate ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

