/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.exchange.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ExchangeRequest
 */
@JsonPropertyOrder( {
        ExchangeRequest.JSON_PROPERTY_FROM,
        ExchangeRequest.JSON_PROPERTY_TO,
        ExchangeRequest.JSON_PROPERTY_REFERENCE,
        ExchangeRequest.JSON_PROPERTY_REQUEST_ID
} )
public class ExchangeRequest
{
    public static final String JSON_PROPERTY_FROM = "from";

    public static final String JSON_PROPERTY_TO = "to";

    public static final String JSON_PROPERTY_REFERENCE = "reference";

    public static final String JSON_PROPERTY_REQUEST_ID = "request_id";

    private ExchangePart from;

    private ExchangePart to;

    private String reference;

    private String requestId;

    public ExchangeRequest from( ExchangePart from )
    {

        this.from = from;
        return this;
    }

    /**
     * Get from
     *
     * @return from
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_FROM )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public ExchangePart getFrom()
    {
        return from;
    }

    public void setFrom( ExchangePart from )
    {
        this.from = from;
    }

    public ExchangeRequest to( ExchangePart to )
    {

        this.to = to;
        return this;
    }

    /**
     * Get to
     *
     * @return to
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_TO )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public ExchangePart getTo()
    {
        return to;
    }

    public void setTo( ExchangePart to )
    {
        this.to = to;
    }

    public ExchangeRequest reference( String reference )
    {

        this.reference = reference;
        return this;
    }

    /**
     * Get reference
     *
     * @return reference
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_REFERENCE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getReference()
    {
        return reference;
    }

    public void setReference( String reference )
    {
        this.reference = reference;
    }

    public ExchangeRequest requestId( String requestId )
    {

        this.requestId = requestId;
        return this;
    }

    /**
     * Get requestId
     *
     * @return requestId
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_REQUEST_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public String getRequestId()
    {
        return requestId;
    }

    public void setRequestId( String requestId )
    {
        this.requestId = requestId;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        ExchangeRequest exchangeRequest = ( ExchangeRequest ) o;
        return Objects.equals( this.from, exchangeRequest.from ) &&
                Objects.equals( this.to, exchangeRequest.to ) &&
                Objects.equals( this.reference, exchangeRequest.reference ) &&
                Objects.equals( this.requestId, exchangeRequest.requestId );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( from, to, reference, requestId );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class ExchangeRequest {\n" );
        sb.append( "    from: " ).append( toIndentedString( from ) ).append( "\n" );
        sb.append( "    to: " ).append( toIndentedString( to ) ).append( "\n" );
        sb.append( "    reference: " ).append( toIndentedString( reference ) ).append( "\n" );
        sb.append( "    requestId: " ).append( toIndentedString( requestId ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

