/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.transaction.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TransactionType
 */
public enum TransactionType
{
    ATM( "atm" ),

    CARD_PAYMENT( "card_payment" ),

    CARD_REFUND( "card_refund" ),

    CARD_CHARGEBACK( "card_chargeback" ),

    CARD_CREDIT( "card_credit" ),

    EXCHANGE( "exchange" ),

    TRANSFER( "transfer" ),

    LOAN( "loan" ),

    FEE( "fee" ),

    REFUND( "refund" ),

    TOPUP( "topup" ),

    TOPUP_RETURN( "topup_return" ),

    TAX( "tax" ),

    TAX_REFUND( "tax_refund" );

    private String value;

    TransactionType( String value )
    {
        this.value = value;
    }

    @JsonCreator
    public static TransactionType fromValue( String value )
    {
        for ( TransactionType b : TransactionType.values() )
        {
            if ( b.value.equals( value ) )
            {
                return b;
            }
        }
        throw new IllegalArgumentException( "Unexpected value '" + value + "'" );
    }

    @JsonValue
    public String getValue()
    {
        return value;
    }

    @Override
    public String toString()
    {
        return String.valueOf( value );
    }
}

