/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.transaction.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * TransactionCard
 */
@JsonPropertyOrder( {
        TransactionCard.JSON_PROPERTY_CARD_NUMBER,
        TransactionCard.JSON_PROPERTY_FIRST_NAME,
        TransactionCard.JSON_PROPERTY_LAST_NAME,
        TransactionCard.JSON_PROPERTY_PHONE
} )
public class TransactionCard
{
    public static final String JSON_PROPERTY_CARD_NUMBER = "card_number";

    public static final String JSON_PROPERTY_FIRST_NAME = "first_name";

    public static final String JSON_PROPERTY_LAST_NAME = "last_name";

    public static final String JSON_PROPERTY_PHONE = "phone";

    private String cardNumber;

    private String firstName;

    private String lastName;

    private String phone;

    public TransactionCard cardNumber( String cardNumber )
    {

        this.cardNumber = cardNumber;
        return this;
    }

    /**
     * Get cardNumber
     *
     * @return cardNumber
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_CARD_NUMBER )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public String getCardNumber()
    {
        return cardNumber;
    }

    public void setCardNumber( String cardNumber )
    {
        this.cardNumber = cardNumber;
    }

    public TransactionCard firstName( String firstName )
    {

        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     *
     * @return firstName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_FIRST_NAME )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getFirstName()
    {
        return firstName;
    }

    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }

    public TransactionCard lastName( String lastName )
    {

        this.lastName = lastName;
        return this;
    }

    /**
     * Get lastName
     *
     * @return lastName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_LAST_NAME )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getLastName()
    {
        return lastName;
    }

    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }

    public TransactionCard phone( String phone )
    {

        this.phone = phone;
        return this;
    }

    /**
     * Get phone
     *
     * @return phone
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_PHONE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getPhone()
    {
        return phone;
    }

    public void setPhone( String phone )
    {
        this.phone = phone;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        TransactionCard transactionCard = ( TransactionCard ) o;
        return Objects.equals( this.cardNumber, transactionCard.cardNumber ) &&
                Objects.equals( this.firstName, transactionCard.firstName ) &&
                Objects.equals( this.lastName, transactionCard.lastName ) &&
                Objects.equals( this.phone, transactionCard.phone );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( cardNumber, firstName, lastName, phone );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class TransactionCard {\n" );
        sb.append( "    cardNumber: " ).append( toIndentedString( cardNumber ) ).append( "\n" );
        sb.append( "    firstName: " ).append( toIndentedString( firstName ) ).append( "\n" );
        sb.append( "    lastName: " ).append( toIndentedString( lastName ) ).append( "\n" );
        sb.append( "    phone: " ).append( toIndentedString( phone ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

