/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.transaction.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * TransactionMerchant
 */
@JsonPropertyOrder( {
        TransactionMerchant.JSON_PROPERTY_NAME,
        TransactionMerchant.JSON_PROPERTY_CITY,
        TransactionMerchant.JSON_PROPERTY_CATEGORY_CODE,
        TransactionMerchant.JSON_PROPERTY_COUNTRY
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.956+01:00[Europe/Bratislava]" )
public class TransactionMerchant
{
    public static final String JSON_PROPERTY_NAME = "name";

    public static final String JSON_PROPERTY_CITY = "city";

    public static final String JSON_PROPERTY_CATEGORY_CODE = "category_code";

    public static final String JSON_PROPERTY_COUNTRY = "country";

    private String name;

    private String city;

    private String categoryCode;

    private String country;


    public TransactionMerchant name( String name )
    {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_NAME )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getName()
    {
        return name;
    }


    public void setName( String name )
    {
        this.name = name;
    }


    public TransactionMerchant city( String city )
    {

        this.city = city;
        return this;
    }

    /**
     * Get city
     *
     * @return city
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_CITY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getCity()
    {
        return city;
    }


    public void setCity( String city )
    {
        this.city = city;
    }


    public TransactionMerchant categoryCode( String categoryCode )
    {

        this.categoryCode = categoryCode;
        return this;
    }

    /**
     * Get categoryCode
     *
     * @return categoryCode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_CATEGORY_CODE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getCategoryCode()
    {
        return categoryCode;
    }


    public void setCategoryCode( String categoryCode )
    {
        this.categoryCode = categoryCode;
    }


    public TransactionMerchant country( String country )
    {

        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_COUNTRY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getCountry()
    {
        return country;
    }


    public void setCountry( String country )
    {
        this.country = country;
    }


    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        TransactionMerchant transactionMerchant = ( TransactionMerchant ) o;
        return Objects.equals( this.name, transactionMerchant.name ) &&
                Objects.equals( this.city, transactionMerchant.city ) &&
                Objects.equals( this.categoryCode, transactionMerchant.categoryCode ) &&
                Objects.equals( this.country, transactionMerchant.country );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( name, city, categoryCode, country );
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class TransactionMerchant {\n" );
        sb.append( "    name: " ).append( toIndentedString( name ) ).append( "\n" );
        sb.append( "    city: " ).append( toIndentedString( city ) ).append( "\n" );
        sb.append( "    categoryCode: " ).append( toIndentedString( categoryCode ) ).append( "\n" );
        sb.append( "    country: " ).append( toIndentedString( country ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

