/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.transaction.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * TransferRequest
 */
@JsonPropertyOrder( {
        TransferRequest.JSON_PROPERTY_REQUEST_ID,
        TransferRequest.JSON_PROPERTY_SOURCE_ACCOUNT_ID,
        TransferRequest.JSON_PROPERTY_TARGET_ACCOUNT_ID,
        TransferRequest.JSON_PROPERTY_AMOUNT,
        TransferRequest.JSON_PROPERTY_CURRENCY,
        TransferRequest.JSON_PROPERTY_REFERENCE
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.956+01:00[Europe/Bratislava]" )
public class TransferRequest
{
    public static final String JSON_PROPERTY_REQUEST_ID = "request_id";

    public static final String JSON_PROPERTY_SOURCE_ACCOUNT_ID = "source_account_id";

    public static final String JSON_PROPERTY_TARGET_ACCOUNT_ID = "target_account_id";

    public static final String JSON_PROPERTY_AMOUNT = "amount";

    public static final String JSON_PROPERTY_CURRENCY = "currency";

    public static final String JSON_PROPERTY_REFERENCE = "reference";

    private String requestId;

    private UUID sourceAccountId;

    private UUID targetAccountId;

    private Double amount;

    private String currency;

    private String reference;


    public TransferRequest requestId( String requestId )
    {

        this.requestId = requestId;
        return this;
    }

    /**
     * Get requestId
     *
     * @return requestId
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_REQUEST_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public String getRequestId()
    {
        return requestId;
    }


    public void setRequestId( String requestId )
    {
        this.requestId = requestId;
    }


    public TransferRequest sourceAccountId( UUID sourceAccountId )
    {

        this.sourceAccountId = sourceAccountId;
        return this;
    }

    /**
     * Get sourceAccountId
     *
     * @return sourceAccountId
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_SOURCE_ACCOUNT_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public UUID getSourceAccountId()
    {
        return sourceAccountId;
    }


    public void setSourceAccountId( UUID sourceAccountId )
    {
        this.sourceAccountId = sourceAccountId;
    }


    public TransferRequest targetAccountId( UUID targetAccountId )
    {

        this.targetAccountId = targetAccountId;
        return this;
    }

    /**
     * Get targetAccountId
     *
     * @return targetAccountId
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_TARGET_ACCOUNT_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public UUID getTargetAccountId()
    {
        return targetAccountId;
    }


    public void setTargetAccountId( UUID targetAccountId )
    {
        this.targetAccountId = targetAccountId;
    }


    public TransferRequest amount( Double amount )
    {

        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_AMOUNT )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Double getAmount()
    {
        return amount;
    }


    public void setAmount( Double amount )
    {
        this.amount = amount;
    }


    public TransferRequest currency( String currency )
    {

        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_CURRENCY )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public String getCurrency()
    {
        return currency;
    }


    public void setCurrency( String currency )
    {
        this.currency = currency;
    }


    public TransferRequest reference( String reference )
    {

        this.reference = reference;
        return this;
    }

    /**
     * Get reference
     *
     * @return reference
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_REFERENCE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getReference()
    {
        return reference;
    }


    public void setReference( String reference )
    {
        this.reference = reference;
    }


    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        TransferRequest transferRequest = ( TransferRequest ) o;
        return Objects.equals( this.requestId, transferRequest.requestId ) &&
                Objects.equals( this.sourceAccountId, transferRequest.sourceAccountId ) &&
                Objects.equals( this.targetAccountId, transferRequest.targetAccountId ) &&
                Objects.equals( this.amount, transferRequest.amount ) &&
                Objects.equals( this.currency, transferRequest.currency ) &&
                Objects.equals( this.reference, transferRequest.reference );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( requestId, sourceAccountId, targetAccountId, amount, currency, reference );
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class TransferRequest {\n" );
        sb.append( "    requestId: " ).append( toIndentedString( requestId ) ).append( "\n" );
        sb.append( "    sourceAccountId: " ).append( toIndentedString( sourceAccountId ) ).append( "\n" );
        sb.append( "    targetAccountId: " ).append( toIndentedString( targetAccountId ) ).append( "\n" );
        sb.append( "    amount: " ).append( toIndentedString( amount ) ).append( "\n" );
        sb.append( "    currency: " ).append( toIndentedString( currency ) ).append( "\n" );
        sb.append( "    reference: " ).append( toIndentedString( reference ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

