/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.draft.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * PaymentOrderInfo
 */
@JsonPropertyOrder( {
        PaymentOrderInfo.JSON_PROPERTY_ID,
        PaymentOrderInfo.JSON_PROPERTY_SCHEDULED_FOR,
        PaymentOrderInfo.JSON_PROPERTY_TITLE,
        PaymentOrderInfo.JSON_PROPERTY_PAYMENTS_COUNT
} )
public class PaymentOrderInfo
{
    public static final String JSON_PROPERTY_ID = "id";

    public static final String JSON_PROPERTY_SCHEDULED_FOR = "scheduled_for";

    public static final String JSON_PROPERTY_TITLE = "title";

    public static final String JSON_PROPERTY_PAYMENTS_COUNT = "payments_count";

    private UUID id;

    private LocalDate scheduledFor;

    private String title;

    private Integer paymentsCount;

    public PaymentOrderInfo id( UUID id )
    {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public UUID getId()
    {
        return id;
    }

    public void setId( UUID id )
    {
        this.id = id;
    }

    public PaymentOrderInfo scheduledFor( LocalDate scheduledFor )
    {

        this.scheduledFor = scheduledFor;
        return this;
    }

    /**
     * Get scheduledFor
     *
     * @return scheduledFor
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_SCHEDULED_FOR )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public LocalDate getScheduledFor()
    {
        return scheduledFor;
    }

    public void setScheduledFor( LocalDate scheduledFor )
    {
        this.scheduledFor = scheduledFor;
    }

    public PaymentOrderInfo title( String title )
    {

        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_TITLE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getTitle()
    {
        return title;
    }

    public void setTitle( String title )
    {
        this.title = title;
    }

    public PaymentOrderInfo paymentsCount( Integer paymentsCount )
    {

        this.paymentsCount = paymentsCount;
        return this;
    }

    /**
     * Get paymentsCount
     *
     * @return paymentsCount
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_PAYMENTS_COUNT )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public Integer getPaymentsCount()
    {
        return paymentsCount;
    }

    public void setPaymentsCount( Integer paymentsCount )
    {
        this.paymentsCount = paymentsCount;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        PaymentOrderInfo paymentOrderInfo = ( PaymentOrderInfo ) o;
        return Objects.equals( this.id, paymentOrderInfo.id ) &&
                Objects.equals( this.scheduledFor, paymentOrderInfo.scheduledFor ) &&
                Objects.equals( this.title, paymentOrderInfo.title ) &&
                Objects.equals( this.paymentsCount, paymentOrderInfo.paymentsCount );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( id, scheduledFor, title, paymentsCount );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class PaymentOrderInfo {\n" );
        sb.append( "    id: " ).append( toIndentedString( id ) ).append( "\n" );
        sb.append( "    scheduledFor: " ).append( toIndentedString( scheduledFor ) ).append( "\n" );
        sb.append( "    title: " ).append( toIndentedString( title ) ).append( "\n" );
        sb.append( "    paymentsCount: " ).append( toIndentedString( paymentsCount ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

