/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.draft.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * PaymentInfo
 */
@JsonPropertyOrder( {
        PaymentInfo.JSON_PROPERTY_ID,
        PaymentInfo.JSON_PROPERTY_AMOUNT,
        PaymentInfo.JSON_PROPERTY_CURRENCY,
        PaymentInfo.JSON_PROPERTY_ACCOUNT_ID,
        PaymentInfo.JSON_PROPERTY_REFERENCE,
        PaymentInfo.JSON_PROPERTY_RECEIVER,
        PaymentInfo.JSON_PROPERTY_STATE,
        PaymentInfo.JSON_PROPERTY_REASON,
        PaymentInfo.JSON_PROPERTY_ERROR_MESSAGE,
        PaymentInfo.JSON_PROPERTY_CURRENT_CHARGE_OPTIONS
} )
@javax.annotation.Generated( value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T19:47:41.599+01:00[Europe/Bratislava]" )
public class PaymentInfo
{
    public static final String JSON_PROPERTY_ID = "id";

    public static final String JSON_PROPERTY_AMOUNT = "amount";

    public static final String JSON_PROPERTY_CURRENCY = "currency";

    public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";

    public static final String JSON_PROPERTY_REFERENCE = "reference";

    public static final String JSON_PROPERTY_RECEIVER = "receiver";

    public static final String JSON_PROPERTY_STATE = "state";

    public static final String JSON_PROPERTY_REASON = "reason";

    public static final String JSON_PROPERTY_ERROR_MESSAGE = "error_message";

    public static final String JSON_PROPERTY_CURRENT_CHARGE_OPTIONS = "current_charge_options";

    private UUID id;

    private Amount amount;

    private String currency;

    private UUID accountId;

    private String reference;

    private PaymentReceiver receiver;

    private PaymentState state;

    private String reason;

    private String errorMessage;

    private PaymentInfoCurrentChargeOptions currentChargeOptions;


    public PaymentInfo id( UUID id )
    {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public UUID getId()
    {
        return id;
    }


    public void setId( UUID id )
    {
        this.id = id;
    }


    public PaymentInfo amount( Amount amount )
    {

        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_AMOUNT )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public Amount getAmount()
    {
        return amount;
    }


    public void setAmount( Amount amount )
    {
        this.amount = amount;
    }


    public PaymentInfo currency( String currency )
    {

        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_CURRENCY )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getCurrency()
    {
        return currency;
    }


    public void setCurrency( String currency )
    {
        this.currency = currency;
    }


    public PaymentInfo accountId( UUID accountId )
    {

        this.accountId = accountId;
        return this;
    }

    /**
     * Get accountId
     *
     * @return accountId
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_ACCOUNT_ID )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public UUID getAccountId()
    {
        return accountId;
    }


    public void setAccountId( UUID accountId )
    {
        this.accountId = accountId;
    }


    public PaymentInfo reference( String reference )
    {

        this.reference = reference;
        return this;
    }

    /**
     * Get reference
     *
     * @return reference
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_REFERENCE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getReference()
    {
        return reference;
    }


    public void setReference( String reference )
    {
        this.reference = reference;
    }


    public PaymentInfo receiver( PaymentReceiver receiver )
    {

        this.receiver = receiver;
        return this;
    }

    /**
     * Get receiver
     *
     * @return receiver
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_RECEIVER )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public PaymentReceiver getReceiver()
    {
        return receiver;
    }


    public void setReceiver( PaymentReceiver receiver )
    {
        this.receiver = receiver;
    }


    public PaymentInfo state( PaymentState state )
    {

        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_STATE )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public PaymentState getState()
    {
        return state;
    }


    public void setState( PaymentState state )
    {
        this.state = state;
    }


    public PaymentInfo reason( String reason )
    {

        this.reason = reason;
        return this;
    }

    /**
     * Get reason
     *
     * @return reason
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_REASON )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getReason()
    {
        return reason;
    }


    public void setReason( String reason )
    {
        this.reason = reason;
    }


    public PaymentInfo errorMessage( String errorMessage )
    {

        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Get errorMessage
     *
     * @return errorMessage
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_ERROR_MESSAGE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )

    public String getErrorMessage()
    {
        return errorMessage;
    }


    public void setErrorMessage( String errorMessage )
    {
        this.errorMessage = errorMessage;
    }


    public PaymentInfo currentChargeOptions( PaymentInfoCurrentChargeOptions currentChargeOptions )
    {

        this.currentChargeOptions = currentChargeOptions;
        return this;
    }

    /**
     * Get currentChargeOptions
     *
     * @return currentChargeOptions
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_CURRENT_CHARGE_OPTIONS )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )

    public PaymentInfoCurrentChargeOptions getCurrentChargeOptions()
    {
        return currentChargeOptions;
    }


    public void setCurrentChargeOptions( PaymentInfoCurrentChargeOptions currentChargeOptions )
    {
        this.currentChargeOptions = currentChargeOptions;
    }


    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        PaymentInfo paymentInfo = ( PaymentInfo ) o;
        return Objects.equals( this.id, paymentInfo.id ) &&
                Objects.equals( this.amount, paymentInfo.amount ) &&
                Objects.equals( this.currency, paymentInfo.currency ) &&
                Objects.equals( this.accountId, paymentInfo.accountId ) &&
                Objects.equals( this.reference, paymentInfo.reference ) &&
                Objects.equals( this.receiver, paymentInfo.receiver ) &&
                Objects.equals( this.state, paymentInfo.state ) &&
                Objects.equals( this.reason, paymentInfo.reason ) &&
                Objects.equals( this.errorMessage, paymentInfo.errorMessage ) &&
                Objects.equals( this.currentChargeOptions, paymentInfo.currentChargeOptions );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( id, amount, currency, accountId, reference, receiver, state, reason, errorMessage, currentChargeOptions );
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class PaymentInfo {\n" );
        sb.append( "    id: " ).append( toIndentedString( id ) ).append( "\n" );
        sb.append( "    amount: " ).append( toIndentedString( amount ) ).append( "\n" );
        sb.append( "    currency: " ).append( toIndentedString( currency ) ).append( "\n" );
        sb.append( "    accountId: " ).append( toIndentedString( accountId ) ).append( "\n" );
        sb.append( "    reference: " ).append( toIndentedString( reference ) ).append( "\n" );
        sb.append( "    receiver: " ).append( toIndentedString( receiver ) ).append( "\n" );
        sb.append( "    state: " ).append( toIndentedString( state ) ).append( "\n" );
        sb.append( "    reason: " ).append( toIndentedString( reason ) ).append( "\n" );
        sb.append( "    errorMessage: " ).append( toIndentedString( errorMessage ) ).append( "\n" );
        sb.append( "    currentChargeOptions: " ).append( toIndentedString( currentChargeOptions ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }

}

