/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.draft.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PaymentInfoCurrentChargeOptions
 */
@JsonPropertyOrder( {
        PaymentInfoCurrentChargeOptions.JSON_PROPERTY_FROM,
        PaymentInfoCurrentChargeOptions.JSON_PROPERTY_TO,
        PaymentInfoCurrentChargeOptions.JSON_PROPERTY_RATE,
        PaymentInfoCurrentChargeOptions.JSON_PROPERTY_FEE
} )
public class PaymentInfoCurrentChargeOptions
{
    public static final String JSON_PROPERTY_FROM = "from";

    public static final String JSON_PROPERTY_TO = "to";

    public static final String JSON_PROPERTY_RATE = "rate";

    public static final String JSON_PROPERTY_FEE = "fee";

    private Amount from;

    private Amount to;

    private String rate;

    private Amount fee;

    public PaymentInfoCurrentChargeOptions from( Amount from )
    {

        this.from = from;
        return this;
    }

    /**
     * Get from
     *
     * @return from
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_FROM )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public Amount getFrom()
    {
        return from;
    }

    public void setFrom( Amount from )
    {
        this.from = from;
    }

    public PaymentInfoCurrentChargeOptions to( Amount to )
    {

        this.to = to;
        return this;
    }

    /**
     * Get to
     *
     * @return to
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_TO )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public Amount getTo()
    {
        return to;
    }

    public void setTo( Amount to )
    {
        this.to = to;
    }

    public PaymentInfoCurrentChargeOptions rate( String rate )
    {

        this.rate = rate;
        return this;
    }

    /**
     * Get rate
     *
     * @return rate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_RATE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public String getRate()
    {
        return rate;
    }

    public void setRate( String rate )
    {
        this.rate = rate;
    }

    public PaymentInfoCurrentChargeOptions fee( Amount fee )
    {

        this.fee = fee;
        return this;
    }

    /**
     * Get fee
     *
     * @return fee
     **/
    @javax.annotation.Nullable
    @ApiModelProperty( value = "" )
    @JsonProperty( JSON_PROPERTY_FEE )
    @JsonInclude( value = JsonInclude.Include.USE_DEFAULTS )
    public Amount getFee()
    {
        return fee;
    }

    public void setFee( Amount fee )
    {
        this.fee = fee;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        PaymentInfoCurrentChargeOptions paymentInfoCurrentChargeOptions = ( PaymentInfoCurrentChargeOptions ) o;
        return Objects.equals( this.from, paymentInfoCurrentChargeOptions.from ) &&
                Objects.equals( this.to, paymentInfoCurrentChargeOptions.to ) &&
                Objects.equals( this.rate, paymentInfoCurrentChargeOptions.rate ) &&
                Objects.equals( this.fee, paymentInfoCurrentChargeOptions.fee );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( from, to, rate, fee );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class PaymentInfoCurrentChargeOptions {\n" );
        sb.append( "    from: " ).append( toIndentedString( from ) ).append( "\n" );
        sb.append( "    to: " ).append( toIndentedString( to ) ).append( "\n" );
        sb.append( "    rate: " ).append( toIndentedString( rate ) ).append( "\n" );
        sb.append( "    fee: " ).append( toIndentedString( fee ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

