/*
 * Revolut for Business OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package biz.turnonline.ecosystem.revolut.business.draft.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PaymentDraftsResponse
 */
@JsonPropertyOrder( {
        PaymentDraftsResponse.JSON_PROPERTY_PAYMENT_ORDERS
} )
public class PaymentDraftsResponse
{
    public static final String JSON_PROPERTY_PAYMENT_ORDERS = "payment_orders";

    private List<PaymentOrderInfo> paymentOrders = new ArrayList<>();

    public PaymentDraftsResponse paymentOrders( List<PaymentOrderInfo> paymentOrders )
    {

        this.paymentOrders = paymentOrders;
        return this;
    }

    public PaymentDraftsResponse addPaymentOrdersItem( PaymentOrderInfo paymentOrdersItem )
    {
        this.paymentOrders.add( paymentOrdersItem );
        return this;
    }

    /**
     * Get paymentOrders
     *
     * @return paymentOrders
     **/
    @ApiModelProperty( required = true, value = "" )
    @JsonProperty( JSON_PROPERTY_PAYMENT_ORDERS )
    @JsonInclude( value = JsonInclude.Include.ALWAYS )
    public List<PaymentOrderInfo> getPaymentOrders()
    {
        return paymentOrders;
    }

    public void setPaymentOrders( List<PaymentOrderInfo> paymentOrders )
    {
        this.paymentOrders = paymentOrders;
    }

    @Override
    public boolean equals( java.lang.Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( o == null || getClass() != o.getClass() )
        {
            return false;
        }
        PaymentDraftsResponse paymentDraftsResponse = ( PaymentDraftsResponse ) o;
        return Objects.equals( this.paymentOrders, paymentDraftsResponse.paymentOrders );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( paymentOrders );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append( "class PaymentDraftsResponse {\n" );
        sb.append( "    paymentOrders: " ).append( toIndentedString( paymentOrders ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

